config/routes.rb
Rails.application.routes.draw do

  root "habits#index"
  resource :user, only: [:new, :create, :edit, :update], path_names: { new: 'sign_up' }
  resources :habits do
    get 'edit_list', on: :collection
  end
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  post 'logout', to:'sessions#destroy'

end

app/models/habit.rb
class Habit < ActiveRecord::Base
	belongs_to :user

	validates :title, presence: true
	validates :goal, numericality: { only_integer: true, greater_then: 0 }
	validates :done, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :period, inclusion: { in: %w(week) }
	validates :kind, inclusion: { in: %w(good bad) }

	before_validation(on: :create) { |habit| habit.done = 0; habit.order = habit.user.habits.length }

	def self.monday_reset
		update_all(done: 0)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :habits

  # validations
  validates :email, uniqueness: true, format: {with: /.+@.+\..+/i}
  validates :password, length: { minimum: 3 }, confirmation: true
  validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def go_to_login
  	redirect_to login_url
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
	before_filter :require_login

	def index
		@habits = current_user.habits.order(:order)
	end

	def edit_list
		@habits = current_user.habits.order(:order)
	end

	def show
		habit = Habit.find(params[:id])
		render json: {:habit => habit}
	end

	def edit
		@habit = Habit.find(params[:id])
		respond_to do |format|
			format.json { render json: {:habit => @habit} }
			format.js
		end
	end

	def create
		@habit = Habit.new(habit_params)
		@habit.user = current_user
		respond_to do |format|
			if @habit.save
				format.js
			else
				format.json { render json: {errors: @habit.errors}, status: 422 }
			end
    end
	end

	def update
		@habit = Habit.find(params[:id])
		@habit.update(habit_params)
		respond_to do |format|
			format.json { render json: @habit }
    end
	end

	def destroy
		@habit = Habit.find(params[:id])
		@habit.destroy
		redirect_to edit_habits_path
	end

private

	def habit_params
		params.require(:habit).permit(:title, :goal, :period, :kind, :done)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
	end

	def create
		if @user = login(params[:email], params[:password])
			redirect_back_or_to(:habits, notice: 'Login successful!' )
		else
			flash.now[:alert] = "Can't find user with this email, or password is incorrect"
			render action: 'new'
		end
	end

	def destroy
		logout
    redirect_to(:users, notice: 'Logged out!')
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			auto_login(@user)
			redirect_to root_path
		else
			render new
		end
	end

	def update
		@user = current_user
		respond_to do |format|
			if @user.update(user_params)
				format.js
			else
				format.json { render json: {errors: @user.errors}, status: 422 }
			end
		end
	end

private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper

	def habit_progress(habit)
		done = habit.done
		goal = habit.goal
		html = ''
		unless goal == nil
			done.times { |i| html << content_tag(:i, nil, class: "icon-#{habit.kind} progress done") }
			(goal-done).times { |i| html << content_tag(:i, nil, class: "icon-#{habit.kind} progress") }
		end
		content_tag(:p, html.html_safe, class: '')
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/habits/_edit.html.erb
<div id="habit-form" class="pure-g modal">
	<div class="pure-u-1">

		<%= form_for :habit, method: :put, remote: true, html: { class: 'pure-form mar-10' } do |f| %>
			<div class="pure-g">
				<div class="pure-u-1-2 center">
					<%= f.label :kind_good, class: 'pure-radio' do %>
						<%= f.radio_button :kind, :good %>
						Good habit
					<% end %>
				</div>
				<div class="pure-u-1-2 center">
					<%= f.label :kind_bad, class: 'pure-radio' do %>
						<%= f.radio_button :kind, :bad %>
						Bad habit
					<% end %>
				</div>
			</div>

			<fieldset>
				<%= f.text_field :title, class: 'pure-input-1 center', placeholder: 'Enter your habit' %>
				<%= f.text_field :goal, class: 'pure-input-1 center', placeholder: 'Your goal (number)' %>
				<div class="pure-control-group center mar-tb-10">
					<%= f.label :period, 'Period to track:' %>
					<%= f.select :period, [['Week', :week]] %>
				</div>
				<div class="center">
					<div class="pure-g">
						<div class="pure-u-1-2">
							<%= f.button :submit, data: { disable_with: "Saving..."}, id: 'save-habit', class: 'pure-input-2-3 pure-button' do %>
								<i class='icon-good'></i> Save
							<% end %>
						</div>
						<div class="pure-u-1-2">
							<%= f.button :submit, id: 'cancel-habit', class: 'pure-input-2-3 pure-button' do %>
								<i class='icon-bad'></i> Cancel
							<% end %>
						</div>
					</div>
				</div>
			</fieldset>
		<% end %>

	</div>
</div>

app/views/habits/_habit.html.erb
<div class="habit <%= habit.kind %>-habit mar-tb-10">
	<div class="pure-g">

		<div class="pure-u-1-2">
			<div class="mar-10">
				<p><%= link_to habit.title, habit, class: 'link habit-link' %></p>
			</div>
		</div>

		<div class="pure-u-1-2">
			<div class="mar-10 center">
				<p><%= habit_progress(habit) %></p>
			</div>
		</div>

	</div>
</div>

app/views/habits/_new.html.erb
<div id="habit-form" class="pure-g modal">
	<div class="pure-u-1">

		<%= form_for :habit, url: habits_path, method: :post, remote: true, html: { class: 'pure-form mar-10' } do |f| %>
			<div class="pure-g">
				<div class="pure-u-1-2 center">
					<%= f.label :kind_good, class: 'pure-radio' do %>
						<%= f.radio_button :kind, :good %>
						Good habit
					<% end %>
				</div>
				<div class="pure-u-1-2 center">
					<%= f.label :kind_bad, class: 'pure-radio' do %>
						<%= f.radio_button :kind, :bad %>
						Bad habit
					<% end %>
				</div>
			</div>

			<fieldset>
				<%= f.text_field :title, class: 'pure-input-1 center', placeholder: 'Enter your habit' %>
				<%= f.text_field :goal, class: 'pure-input-1 center', placeholder: 'Your goal (number)' %>
				<div class="pure-control-group center mar-tb-10">
					<%= f.label :period, 'Period to track:' %>
					<%= f.select :period, [['Week', :week]] %>
				</div>
				<div class="center">
					<div class="pure-g">
						<div class="pure-u-1-2">
							<%= f.button :submit, data: { disable_with: "Saving..."}, id: 'save-habit', class: 'pure-input-2-3 pure-button' do %>
								<i class='icon-good'></i> Save
							<% end %>
						</div>
						<div class="pure-u-1-2">
							<%= f.button :submit, id: 'cancel-habit', class: 'pure-input-2-3 pure-button' do %>
								<i class='icon-bad'></i> Cancel
							<% end %>
						</div>
					</div>
				</div>
			</fieldset>
		<% end %>

	</div>
</div>

app/views/habits/edit.html.erb
<% @habits.each do |habit| %>
	<div class="habit <%= habit.kind %>-habit mar-tb-10">
		<div class="pure-g">

			<div class="pure-u-1-2">
				<div class="mar-10">
					<p><%= link_to habit.title, habit, class: 'link' %></p>
				</div>
			</div>

			<div class="pure-u-1-2">
				<div class="mar-10 center">
					<%= link_to 'Edit', habit, class: 'pure-button edit-habit-link' %>
					<%= link_to 'Destroy', habit, method: :delete, class: 'pure-button' %>
				</div>
			</div>

		</div>
	</div>
<% end %>

app/views/habits/edit_list.html.erb
<% @habits.each do |habit| %>
	<div class="habit <%= habit.kind %>-habit mar-tb-10">
		<div class="pure-g">

			<div class="pure-u-1-2">
				<div class="mar-10">
					<p><%= link_to habit.title, habit, class: 'link' %></p>
				</div>
			</div>

			<div class="pure-u-1-2">
				<div class="mar-10 center">
					<%= link_to 'Edit', habit, class: 'pure-button edit-habit-link', data: {id: habit.id} %>
					<%= link_to 'Destroy', habit, method: :delete, class: 'pure-button' %>
				</div>
			</div>

		</div>
	</div>
<% end %>

<%= render 'edit' %>

app/views/habits/index.html.erb
<div id="new-habits">
	<div class="pure-g">

		<div class="pure-u-1-2">
			<div class="mar-10 center">
				<%= link_to "Add good habit", nil, class: 'pure-button good-button' %>
			</div>
		</div>

		<div class="pure-u-1-2">
			<div class="mar-10 center">
				<%= link_to "Add bad habit", nil, class: 'pure-button bad-button' %>
			</div>
		</div>

	</div>
</div>

<div id="habits">
	<%= render @habits %>
</div>

<div class="pure-g">
	<div class="pure-u-1 right">
		<div id="edit-habits-link">
			<%= link_to 'Edit your habit list', edit_list_habits_path %>
		</div>
	</div>
</div>

<%= render 'new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <title>Habits Tracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="pure-g header-container">
      <div class="pure-u-1 container header">
        <h1 class="app-title"><%= link_to "Habit<span class='red'>Track</span>".html_safe, root_path  %></h3>
        <% if current_user %>
          <div class="header-menu">
            <i id='menu' class='icon-cog'></i>
          </div>
        <% end %>
      </div>
  </div>

  <div id="overlay"></div>
  <div class="container">
		<%= yield %>
	</div>

<% if current_user %>
  <div id="settings" class="pure-g modal">
    <div class="pure-u-1">
      <h3 class="center">Edit profile</h3>
      <%= form_for current_user, remote: true, html: { class: 'pure-form pure-form-aligned', id: 'settings-form'} do |f| %>
        <fieldset>
          <div class="pure-control-group">
            <%= f.label :email %>
            <%= f.text_field :email %>
          </div>
          <div class="pure-control-group">
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>
          <div class="pure-control-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
          </div>
          <div class="pure-control-group">
            <label></label>
            <%= f.submit 'Save', class: 'pure-button', data: { disable_with: "Saving..."} %>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
<% end %>

<div>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
</div>

</body>
</html>

app/views/users/new.html.erb
<div class="pure-g mar-10">
	<div class="pure-u-1 pure-u-md-1-2">
		<h1>Sign up</h1>
		<p><%= link_to 'Login', login_path %></p>
	</div>

	<div class="pure-u-1 pure-u-md-1-2">

		<%= form_for @user, url: user_path, html: { class: 'pure-form pure-form-aligned' } do |f| %>
			<fieldset>
				<div class="pure-control-group">
					<%= f.label :email, "Email" %>
					<%= f.text_field :email %>
				</div>
				<div class="pure-control-group">
					<%= f.label :password, "Password" %>
					<%= f.password_field :password %>
				</div>
				<div class="pure-control-group">
					<%= f.label :password_confirmation, "Password Confirmation" %>
					<%= f.password_field :password_confirmation %>
				</div>
				<div class="pure-control-group">
					<label></label>
					<%= f.submit "Sign up", class: 'pure-button pure-button-primary', :disable_with => 'Submiting...' %>
				</div>
			</fieldset>
		<% end %>

	</div>
</div>